version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance_me
